{% set version = "1.1.0" %}

package:
  name: py-serializable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/py-serializable/py_serializable-{{ version }}.tar.gz
  sha256: 3311ab39063b131caca0fb75e2038153682e55576c67f24a2de72d402dccb6e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.8.1
    - python >=3.8
  run:
    - defusedxml >=0.7.1,<0.8.0
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - serializable
  commands:
    - pip check
    - mypy -p serializable
    - coverage run --source=serializable --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=83
  requires:
    - coverage
    - lxml
    - mypy
    - pip
    - pytest
    - xmldiff

about:
  home: https://github.com/madpah/serializable
  summary: Library for serializing and deserializing Python Objects to and from JSON and XML.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://py-serializable.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
