{% set version = "1.1.2" %}

package:
  name: py-serializable
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/py-serializable/py_serializable-{{ version }}.tar.gz
  sha256: 89af30bc319047d4aa0d8708af412f6ce73835e18bacf1a080028bb9e2f42bdb

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.8.1
    - python {{ python_min }}
  run:
    - defusedxml >=0.7.1,<0.8.0
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - coverage
    - lxml
    - mypy
    - pip
    - pytest
    - xmldiff
    - python {{ python_min }}
  imports:
    - serializable
  commands:
    - pip check
    - mypy -p serializable
    - coverage run --source=serializable --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=82

about:
  home: https://github.com/madpah/serializable
  summary: Library for serializing and deserializing Python Objects to and from JSON and XML.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://py-serializable.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
